### ISSUE TITLE
(string) numbers with commas are not parsed correctly

### ISSUE THREAD

**Issue by techieshark** [nickslevine/zebras#40]
Perhaps this should just go in the docs, but "1,200.30" turns into `1`. Thanks, `parseFloat`!

Observe:
```
> z.parseNums(['amount'], [{amount: '1,200.30'}])
[ { amount: 1 } ]
```

There's a US-centric way to handle this (https://stackoverflow.com/a/11665949/1024811) or a much heavier I18N way to do it (https://stackoverflow.com/a/42000120/1024811), or people could just be warned that columns should not have commas in them.

**Comment by amytych** [comment]
Thanks for pointing that out @techieshark!

I think we might be better of with using `+` for parsing numbers, since indeed it behaves better than `parseFloat`. I don't think we should go as far as trying to handle formatted numbers, we could mention that in the docs.

What do you think @nickslevine?

**Comment by nickslevine** [comment]
Thanks for pointing out, @techieshark! 

@amytych Seems as if the `+` operator doesn't fix the problem with the commas in number-strings, unless I'm missing something? 

Couldn't hurt to put a warning in the docs to start and then file an enhancement issue for smarter parsing? What do you both think?

**Comment by amytych** [comment]
> Seems as if the + operator doesn't fix the problem with the commas in number

Hehe, yes, I'm aware, I just meant it's better in a way that it returns `NaN` when it can't parse a string as a number, which seems more appropriate than a totally incorrect number like `parseFloat` does, e.g:

<img width="174" alt="image" src="https://user-images.githubusercontent.com/998924/75318131-e2e9b980-5869-11ea-9777-e01b724600a5.png">

As for the smarter parsing I'm worried it might be a mine field and out of scope of this library. Dealing with localized formats might be too much of a hustle, as also pointed out in the SO thread linked in the issue it's not trivial to do in a reliable manner. (tldr: commas might mean very different things in formatted strings)

**Comment by amytych** [comment]
One more note, seems that using `+` would make it behave similar to `pandas.to_numeric()` with `errors="coerce"` setting?

https://repl.it/repls/VainWiltedSeptagon
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html

**Comment by nickslevine** [comment]
@amytych cool cool, that all makes a lot of sense!

**Comment by nickslevine** [comment]
Just switched parseFloat() with + and added a note re:commas in the README. @techieshark thanks for flagging!

@amytych - I wasn't quite sure how to update the docs website - mind reminding me how the build process works? Thanks!

**Comment by amytych** [comment]
Great you actioned this @nickslevine, thanks!

I'd still consider a PR route even for such a seemingly small case, some things worth thinking about a bit more here:

- improving tests to cover as many edge cases as possible
- should we consider handling empty strings? `+"" === 0` ☹️ 
- when releasing we should perhaps bump the major version since it might not be backwards compatible?
- worth explaining the behavior a bit more within the `parseNums` docs as well (or at least repeat what you've put in the main README)?

I'll look into publishing new docs 👍

**Comment by nickslevine** [comment]
That all makes sense - sound good!
